services:
    application:
        build:
            context: .
            dockerfile: ./.docker/app/Dockerfile
        volumes:
            - .:/var/www

    nginx:
        build:
            context: ./.docker/nginx
            dockerfile: Dockerfile
        expose:
            - "80"
        ports:
            - "${FORWARD_NGINX_PORT:-80}:80"
        volumes:
            - ./.docker/nginx/site.conf:/site.conf
        volumes_from:
            - application
        depends_on:
            - php-fpm
        working_dir: /var/www
        stop_grace_period: 1s
        environment:
            - ENV_NGINX_PHP_CONTAINER_HOST=php-fpm
            - ENV_NGINX_HOST=localhost
            - ENV_NGINX_PUBLIC_PATH=public
            - CRONTAB_LARAVEL_SCHEDULER_ENABLED=true
        networks:
            - messenger

    php-fpm:
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
            - ./.docker/php/fpm-site.conf:/usr/local/etc/php-fpm.d/900-site.conf
        working_dir: /var/www
        expose:
            - "9000"
        labels:
            traefik.enable: "false"
        user: '1000'
        tty: true
        environment:
            - PHP_FPM_PM_MODE=dynamic
            - PHP_FPM_PM_MAX_CHILDREN=20
        networks:
            - messenger

    master:
        container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
        build:
            context: ./.docker/citus
            dockerfile: Dockerfile
        ports: ["${COORDINATOR_EXTERNAL_PORT:-5432}:5432"]
        labels: ["com.citusdata.role=Master"]
        environment: &AUTH
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            PGUSER: "${DB_USERNAME}"
            PGPASSWORD: "${DB_PASSWORD}"
            POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
        networks:
            - messenger

    manager:
        container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
        image: "citusdata/membership-manager:0.3.0"
        volumes:
            - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
            - healthcheck-volume:/healthcheck
        depends_on: [master]
        environment: *AUTH
        networks:
            - messenger

    worker:
        build:
            context: ./.docker/citus
            dockerfile: Dockerfile
        labels: ["com.citusdata.role=Worker"]
        depends_on: [manager]
        volumes:
            - healthcheck-volume:/healthcheck
        command: "/wait-for-manager.sh"
        environment: *AUTH
        networks:
            - messenger

    postgresql-testing:
        image: postgres:16.4
        environment:
            POSTGRES_DB: ${TESTING_DB_DATABASE}
            POSTGRES_USER: ${TESTING_DB_USERNAME}
            POSTGRES_PASSWORD: ${TESTING_DB_PASSWORD}
            PGDATA: /data/postgres
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d ${TESTING_DB_DATABASE} -U ${TESTING_DB_USERNAME}" ]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always
        volumes:
            - pg_vol-testing:/data/postgres
        ports:
            - "${TESTING_FORWARD_DB_PORT:-54322}:5432"
        networks:
            - messenger

networks:
    messenger:
        driver: bridge

volumes:
    healthcheck-volume:
        driver: "local"
    pg_vol:
        driver: "local"
    pg_vol-testing:
        driver: "local"
